/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // All semantic colors reference CSS custom properties so they
        // flip automatically when the .dark class is applied to <html>.
        // Variables are defined in globals.css as space-separated RGB channels
        // so Tailwind's opacity modifier syntax (bg-primary/50) still works.
        "background":                  "rgb(var(--col-background) / <alpha-value>)",
        "surface":                     "rgb(var(--col-surface) / <alpha-value>)",
        "surface-variant":             "rgb(var(--col-surface-variant) / <alpha-value>)",
        "surface-dim":                 "rgb(var(--col-surface-dim) / <alpha-value>)",
        "surface-bright":              "rgb(var(--col-surface-bright) / <alpha-value>)",
        "surface-container-lowest":    "rgb(var(--col-surface-container-lowest) / <alpha-value>)",
        "surface-container-low":       "rgb(var(--col-surface-container-low) / <alpha-value>)",
        "surface-container":           "rgb(var(--col-surface-container) / <alpha-value>)",
        "surface-container-high":      "rgb(var(--col-surface-container-high) / <alpha-value>)",
        "surface-container-highest":   "rgb(var(--col-surface-container-highest) / <alpha-value>)",
        "surface-tint":                "rgb(var(--col-surface-tint) / <alpha-value>)",
        "on-surface":                  "rgb(var(--col-on-surface) / <alpha-value>)",
        "on-surface-variant":          "rgb(var(--col-on-surface-variant) / <alpha-value>)",
        "on-background":               "rgb(var(--col-on-background) / <alpha-value>)",
        "outline":                     "rgb(var(--col-outline) / <alpha-value>)",
        "outline-variant":             "rgb(var(--col-outline-variant) / <alpha-value>)",
        "inverse-surface":             "rgb(var(--col-inverse-surface) / <alpha-value>)",
        "inverse-on-surface":          "rgb(var(--col-inverse-on-surface) / <alpha-value>)",
        "inverse-primary":             "rgb(var(--col-inverse-primary) / <alpha-value>)",
        "primary":                     "rgb(var(--col-primary) / <alpha-value>)",
        "on-primary":                  "rgb(var(--col-on-primary) / <alpha-value>)",
        "primary-container":           "rgb(var(--col-primary-container) / <alpha-value>)",
        "on-primary-container":        "rgb(var(--col-on-primary-container) / <alpha-value>)",
        "primary-fixed":               "rgb(var(--col-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim":           "rgb(var(--col-primary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed":            "rgb(var(--col-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant":    "rgb(var(--col-on-primary-fixed-variant) / <alpha-value>)",
        "secondary":                   "rgb(var(--col-secondary) / <alpha-value>)",
        "on-secondary":                "rgb(var(--col-on-secondary) / <alpha-value>)",
        "secondary-container":         "rgb(var(--col-secondary-container) / <alpha-value>)",
        "on-secondary-container":      "rgb(var(--col-on-secondary-container) / <alpha-value>)",
        "secondary-fixed":             "rgb(var(--col-secondary-fixed) / <alpha-value>)",
        "secondary-fixed-dim":         "rgb(var(--col-secondary-fixed-dim) / <alpha-value>)",
        "on-secondary-fixed":          "rgb(var(--col-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant":  "rgb(var(--col-on-secondary-fixed-variant) / <alpha-value>)",
        "tertiary":                    "rgb(var(--col-tertiary) / <alpha-value>)",
        "on-tertiary":                 "rgb(var(--col-on-tertiary) / <alpha-value>)",
        "tertiary-container":          "rgb(var(--col-tertiary-container) / <alpha-value>)",
        "on-tertiary-container":       "rgb(var(--col-on-tertiary-container) / <alpha-value>)",
        "tertiary-fixed":              "rgb(var(--col-tertiary-fixed) / <alpha-value>)",
        "tertiary-fixed-dim":          "rgb(var(--col-tertiary-fixed-dim) / <alpha-value>)",
        "on-tertiary-fixed":           "rgb(var(--col-on-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant":   "rgb(var(--col-on-tertiary-fixed-variant) / <alpha-value>)",
        "error":                       "rgb(var(--col-error) / <alpha-value>)",
        "on-error":                    "rgb(var(--col-on-error) / <alpha-value>)",
        "error-container":             "rgb(var(--col-error-container) / <alpha-value>)",
        "on-error-container":          "rgb(var(--col-on-error-container) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "verse-padding": "0.5rem",
        "content-margin": "2rem",
        "sidebar-width": "280px",
        "sidebar-collapsed": "64px",
        "pane-gap": "1px",
        "touch-target": "32px",
      },
      fontFamily: {
        "body-reading": ['"Source Serif 4 Variable"', "serif"],
        "body-ui": ['"Hanken Grotesk Variable"', "sans-serif"],
        "display-lg": ['"Hanken Grotesk Variable"', "sans-serif"],
        "metadata-mono": ['"JetBrains Mono Variable"', "monospace"],
        "headline-md": ['"Hanken Grotesk Variable"', "sans-serif"],
        "verse-number": ['"Hanken Grotesk Variable"', "sans-serif"],
      },
      fontSize: {
        "body-reading": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-ui": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "metadata-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "verse-number": ["11px", { lineHeight: "1.0", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
